### ISSUE TITLE
1.2.4_타입스크립트를 사용하면 어떤 장점이 있을까요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#1]
📝 30p

❓ 자바스크립트와 비교했을 때, 타입스크립트를 사용하면 어떤 장점이 있을까요?

---

**Comment by 42inshin** [comment]
타입스크립트는 자바스크립트의 슈퍼셋으로 자바스크립트의 기능을 포함하면서도 추가 기능을 제공합니다.
- **안정성이 보장됩니다.** 자바스크립트는 동적 타입 언어라 값이 할당될 때 타입이 결정되지만, 타입스크립트는 컴파일 단계를 거치면서 타입의 오류를 검사해 런타임 에러를 줄일 수 있습니다.
- **개발 생산성을 높일 수 있습니다.** VScode와 같은 IDE에서 기본 제공되고, 타입 자동완성과, 타입 추론이 되기 때문에 타입을 바로 확인할 수 있습니다.
- **협업에 유리합니다.** 데코레이터, 제네릭, 인터페이스 등의 기능을 제공하고 있어서 코드 가독성을 높일 수 있습니다.
이러한 장점들로 구조적이고 일관된 코드를 작성할 수 있어서 **대규모 프로젝트에 사용하기에 유리**합니다.

**Comment by jnkeniaem** [comment]
동적 타입 언어인 자바스크립트와는 다르게 타입스크립트는 정적 타이핑을 제공해 컴파일 단계에서 변수나 함수의 타입의 검사가 수행됩니다. 따라서 자바스크립트를 사용할때 자주 발생하는 타입 에러를 줄일 수 있고, 런타임 에러를 예방할 수 있어 안정성이 크게 높아집니다.
또한, 타입을 통해 코드의 의도를 명확하게 전달할 수 있기때문에 코드 파악이 보다 더 잘 돼서 협업 효율성이 향상됩니다.
