### ISSUE TITLE
4.2_타입을 좁히는 방법들(타입 가드)에 대해서 설명하시오.

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#10]
📝 132p

❓ 타입 가드를 사용하면 객체의 타입을 좁혀나갈 수 있습니다. 
자바스크립트 연산자를 이용한 3가지 타입 가드와 사용자 정의 타입가드가 있는데, 어떤 연산자를 사용하나요? 
그리고, 각각에 대해 간단히 설명해주세요.

**Comment by 42inshin** [comment]
자바스크립트 연산자에 typeof, instanceof, in을 사용해 타입 가드를 할 수 있다. 
- typeof: 원시 타입으로 추론
- instanceof: 인스턴스화된 객체 타입 판별
- in: 객체에 속성의 유무 파악

그리고, 사용자 정의 타입가드는 is를 사용해 만들 수 있다.
- A is B: A 매개변수가 B 타입인지 아닌지 확인

```ts
const isCat = (x: Cat | Dog): x is Cat => { // 타입스크립트에게 반환값의 타입 정보를 알려줄 수 있다!
  return (x as Cat).meow !== undefined
};
```

**Comment by jnkeniaem** [comment]
typeof, instanceof, in 그리고 is 연산자를 사용합니다.

원시 타입을 좁힐땐 typeof 연산자를, 객체 타입을 판별할 때는 instanceof 연산자를, 객체에 속성이 있는지 확인할 때는 in 연산자를 사용합니다.
사용자 정의 타입 가드의 경우, 반환 타입을 `A is B`, `매개변수 이름 is 타입`과 같은 형태로 하는 타입 가드 함수를 만들어 사용할 수 있습니다.
