### ISSUE TITLE
4.1.1_타입 확장에 대해, 그리고 타입 확장을 했을때의 장점을 설명해주세요

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#11]
📝 120p

❓ 타입 확장에 대해, 그리고 타입 확장을 했을때의 장점을 설명해주세요

**Comment by 42inshin** [comment]
기존타입을 확장해서 관련된 타입을 만들 수 있어서 "코드 중복"을 줄일 수 있고, 공통된 변경 사항이 있는 경우, 한번에 바꿀 수 있어서 "유지보수에 용이"합니다.

**Comment by jnkeniaem** [comment]
불필요한 코드 중복을 줄일 수 있고, 명시적인 코드를 작성할 수 있습니다.
