### ISSUE TITLE
5.5 유틸리티 타입에서 Record, Partial, Pick, Omit 에 대해 설명하시오.

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#12]
📝 179p

❓ 유틸리티 타입을 활용하면 여러가지 커스텀 유틸리티 타입들을 만들 수 있습니다. 그 중 대표적인 Record, Partial, Pick, Omit에 대해 간단히 설명해주세요.

**Comment by 42inshin** [comment]
**Record** : Record<K, T>는 키 타입 K와 값 타입 T를 가지는 객체 타입을 정의하는데 사용됩니다. 인덱스 시그니처와 유사한 기능을 합니다.

**Partial**: Partial 타입은 객체의 모든 속성을 옵셔널하게 만들어 타입을 정의합니다. 속성 값이 없는 경우, 해당 값은 undefined 입니다.

**Pick**: 특정 타입에서 몇 개의 속성을 선택하여 타입을 정의할 수 있습니다.

**Omit**: 특정 타입에서 지정된 속성만 제거해서 타입을 정의합니다.

참조: https://joshua1988.github.io/ts/usage/utility.html#%EC%9E%90%EC%A3%BC-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EC%9C%A0%ED%8B%B8%EB%A6%AC%ED%8B%B0-%ED%83%80%EC%9E%85-%EB%AA%87-%EA%B0%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0

https://cheeseb.github.io/typescript/typescript-record/

**Comment by jnkeniaem** [comment]
`Record<K, T>`
특정 키 집합과 그에 할당된 타입을 정의할 때 사용합니다. 지정된 키에 대해 모두 같은 타입을 할당할 수 있습니다.

`Partial<T>`
모든 프로퍼티를 선택적으로 만들 때 사용합니다. 원래 필수적인 속성들도 옵셔널로 바꿀 수 있습니다.

`Pick<T, K>`
기존 타입에서 특정 프로퍼티만 선택하여 새로운 타입을 만들 때 사용합니다.

`Omit<T, K>`
기존 타입에서 특정 프로퍼티만 제외하고 새로운 타입을 만들 때 사용합니다.
