### ISSUE TITLE
5.1_조건부 타입의 문법과 사용법을 설명해주세요

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#13]
📝 150p

❓ 조건부 타입의 문법과 사용법을 설명해주세요

ex) `T extends U ? X : Y`

**Comment by jnkeniaem** [comment]
자바스크립트의 삼항 연산자와 동일하게 `Condition ? A : B` 형태를 가지고, `Condition`이 `true`일때 `A` 타입이, 아니면 `B` 타입이 반환됩니다.

상황에 따라 적절한 타입을 얻기 위해 사용합니다

**Comment by 42inshin** [comment]
`T extends U ? X : Y` 조건부 타입의 기본형태는 이렇습니다. 타입을 동적으로 결정할 때 사용합니다.

타입 T 가 타입 U에 할당 가능할 때 타입 X를 반환하고, 그렇지 않을 때 타입 Y를 반환합니다. 

특정 타입에 맞는 반환 타입을 반환할 때 사용하거나, 객체의 속성들의 타입을 바꿀 때 등등에 사용됩니다.
