### ISSUE TITLE
6.2.2_타입스크립트 컴파일러(tsc)와 바벨(Babel)의 차이

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#14]
📝 191p

❓ 자바스크립트 컴파일러로 알려져 있는 바벨(Babel)과 타입스크립트 컴파일러(tsc)의 차이는 뭘까요? 바벨이 tsc를 대신할 수는 없을까요?

**Comment by jnkeniaem** [comment]
바벨은 tsc와 달리 타입 검사를 하지 않습니다.

**Comment by 42inshin** [comment]
tsc는 타입 검사와 코드 변환 두가지를 수행할 수 있는 반면에, 바벨은 최신 자바스크립트를 오래된 브라우저에 호환할 수 있게 구 버전 자바스크립트(ES5 이하)로 코드를 변환해 줍니다. 트랜스파일을 수행하지만 타입 검사를 하지 않는 바벨이 tsc를 대신하는데에는 어려움이 있습니다.
