### ISSUE TITLE
6.2_tsc는 주로 어떤 역할을 하나요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#15]
📝 191p

❓tsc는 주로 어떤 역할을 하나요?
핵심 역할 위주로 설명해주세요.

**Comment by jnkeniaem** [comment]
코드의 타입 에러를 검사하고, 최신 버전의 타입 스크립트 또는 자바스크립트 코드를 구버전의 자바스크립트로 변환합니다.

**Comment by 42inshin** [comment]
타입스크립트 컴파일러는 "타입 검사"와 "코드 변환"을 수행할 수 있습니다.
