### ISSUE TITLE
3.3_타입스크립트 컴파일러 실행 과정을 설명하세요

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#16]
📝 192p

❓ 타입스크립트 컴파일러의 실행 과정에 대해서 간단히 설명해 주세요.

**Comment by 42inshin** [comment]
tsc 명령어를 치면, 5가지 단계를 수행합니다.
첫번째로, 스캐너 단계에서 .ts 파일을 읽어 토큰을 만들고,
파서 단계에서 토큰을 이용해 구문을 해석해서 추상 구문 트리(AST)를 만듭니다.
바인더 단계에서 AST 노드 기반으로 심볼을 생성하고,
체커 단계에서 AST와 심볼을 기반으로 타입 검사를 수행합니다.
마지막으로 이미터 단계에서 AST와 타입 검사 결과를 바탕으로 자바스크립트 코드를 생성합니다.

**Comment by jnkeniaem** [comment]
1. tsc 명령어로 컴파일 과정을 시작
2. 소스 파일을 어휘적으로 분석해서 토큰 생성
3. 생성된 토큰을 구문적으로 분석해 ast 생성
4. ast 노드 기반으로 심볼 생성
5. 이전 단계에서 생성한 ast와 심볼을 기반으로 타입 검사 수행
6. 타입 검사에 오류가 없으면 타입스크립트 소스 파일로 자바스크립트 파일 생성
