### ISSUE TITLE
7.1_API 호출하는 코드를 React 프로젝트에 넣을때, 가독성과 유지보수성을 높이기 위해어떤 구조로 짤 것인가?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#17]
📝 200p

❓ 백엔드에서 API 호출하는 코드를 React 프로젝트에 넣으려고 합니다. 면접자분이 이걸 담당했다고 가정했을 때, 어떤 구조로 코드를 구성할 것인가요?
가독성과 유지보수성을 초점으로 두고, 프로젝트 내에 만들 폴더 또는 파일 구조나 사용할 라이브러리 등을 말씀해 주시고 이유도 함께 말씀해 주세요.

**Comment by 42inshin** [comment]
컴포넌트는 UI에 집중할 수 있도록 API 호출 로직을 컴포넌트와 구분지어서 관리하겠습니다.
서비스 레이어를 만들어서 API 호출 로직을 한 곳에서 관리할 예정이며, 호스트 URL은 환경변수로 빼서 관리하겠습니다.
axios 라이브러리를 사용해서 여러 서버에 호출을 하는 경우도 호응할 수 있도록 인스턴스화 해서 api config를 각 서버에 맞게 관리하겠습니다.
인터셉터 기능을 이용해서 요청, 응답에 필요한 추가 인증이나 로직들을 관리하고,
필요하다면 react-query와 같은 라이브러리로 데이터 캐싱 및 api에 따른 뷰 상태 관리를 하도록 할 예정입니다.

**Comment by jnkeniaem** [comment]
저는 api 호출 부분을 컴포넌트 영역외의 다른 영역, 즉 서비스 레이어에서 처리할것같습니다. api 호출 로직이 서비스 레이어에 있기 때문에 api 관련 정책이 변경될 경우, 한 곳만 수정하면 됩니다. 이를 통해 유지보수 시 수정 범위가 최소화됩니다.

그리고 axios 라이브러리를 사용할것같습니다. 그리고 api 에러를 처리할 때 하나의 에러 객체로 묶어서 편리하게 처리할 수 있는 인터셉터 기능이 있기 때문입니다.
