### ISSUE TITLE
7.1.6_런타임 오류를 미리 잡아내지 못하는건 타입스크립트의 어떤 특징 때문인가요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#18]
📝 213p

❓ 질문
개발 단계에서는 api 응답 형식이 자주 바뀝니다. 예를 들어 api 응답 값의 타입이 string이어야 하는데 number가 들어오는 것 같이 잘못된 타입이 전달되는 등. 그러나 타입스크립트는 런타임에서 발생하는 오류는 찾아낼 수 없습니다. 오류를 미리 잡아내지 못하는건 타입스크립트의 어떤 특징 때문인가요? 그리고, 그에 대한 해결방법을 말해주세요.

**Comment by 42inshin** [comment]
타입스크립트는 컴파일 단계에서 타입을 검사하는 정적 타입 검사기이기 때문에, API 호출을 하는 런타임 상황에서는 타입의 정확성을 판별하기 어렵습니다. 이런 경우에 도움을 줄 수 있는 라이브러리들이 있는데, superstruct, zod 등이 있으며 superstruct로 예시를 들면, 라이브러리 내에 타입을 검사할 수 있는 is, assert, validate 와 같은 데이터 유효성을 검사할 수 있는 모듈을 제공해주기 때문에 이러한 런타임 타입 검사 라이브러리를 이용하면 에러를 캐치할 수 있습니다.

**Comment by jnkeniaem** [comment]
타입스크립트는 정적으로 타입 검사를 하기 때문에 런타임 말고 컴파일 단계에서 코드의 타입을 검증해서 입니다. 사용해본적은 없지만, 해당 에러를 방지하는, 런타임에서의 데이터 유효성 검사를 통해 개발자에게 자세한 런타임 에러를 보여주는  Superstruct 같은 라이브러리가 있다고 들었습니다.
