### ISSUE TITLE
7.3.7_비즈니스 로직에서 200 응답과 함께 에러를 처리해야 하는 경우, 어떤 방식으로 처리하면 좋을까?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#19]
📝 236p

❓저희 주문 쪽 비지니스 로직의 경우, 재고가 없는 경우에는 상태 코드를 200으로 주지만 응답 바디에 따로 커스텀 에러 코드와 에러 메시지를 넣어서 클라이언트에 보내고 있습니다. 이러한 정상적인 요청 응답에서의 에러를 어떤 방식으로 처리할건지 고민해보고 말씀해주세요.

**Comment by 42inshin** [comment]
해당 호스트에 요청하는 함수에서 커스텀 에러 코드에 따라 에러를 컨트롤할 수 있도록 조건을 걸어서 처리할 수 있을 것 같습니다.
만약에 해당 도메인(주문 관련 비즈니스 로직들)에서 동일한 커스텀 에러 코드를 준다면, api 요청 인스턴스를 따로 만들어서 인터셉터에서 에러를 핸들링하겠습니다. 더 나아가서 에러 코드에 따라 각 국가별로 다른 메시지를 전달해야 하는 경우라면, 해당 코드에 따라 맞춤형 메시지가 나오도록 분기를 처리하는 함수를 만들어 추가할 것 같습니다.

**Comment by jnkeniaem** [comment]
api 요청하는 부분에서 조건문으로 커스텀 에러 코드를 비교해 에러를 처리할 것 같습니다.

**Comment by 42inshin** [comment]
1. api 호출 함수에서 조건문으로 분기 처리
2. 에러 전용 함수 만들어서 try 내에 함수 추가
3. axios 인터셉터에서 처리

기타) 에러 코드에 따라 메시지를 커스텀해야 한다면, 에러 코드에 따라서 맞춤 메시지가 나오도록 처리하는 것도 고려해볼 수 있다.
