### ISSUE TITLE
1.2.4_타입스크립트에서의 인터페이스에 대해 설명해주세요

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#2]
📝 31p

❓ 타입스크립트에서의 인터페이스에 대해 설명해주세요

[참고 링크](https://ghvhdh321.tistory.com/entry/%EA%B8%B0%EC%88%A0-%EB%A9%B4%EC%A0%91-%EC%A4%80%EB%B9%84-4-Front-end#article-10--q--%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%9D%98-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)

**Comment by jnkeniaem** [comment]
타입스크립트에서 인터페이스는 객체 구조를 정의합니다.
즉, 특정 객체가 가져야 하는 프로퍼티와 메서드의 집합을 정의해서 객체가 그 구조를 따르게 합니다.

**Comment by 42inshin** [comment]
interface는 객체의 구조를 정의하는데 사용합니다.
인터페이스 내에 객체가 가져야할 속성과 타입을 명시해 사용합니다.
```ts
interface Person {
  name: string;
  age: number;
}

let person: Person = { name: "Alice", age: 30 };
```

추가적인 기능으로는 속성을 **옵셔널(`?`)**, **읽기전용(`readonly`)** 으로 정의할 수 있습니다.
**함수 타입을 정의**할 수 있으며 **클래스 구조 정의**와 **인터페이스 확장** 에도 사용할 수 있습니다.
