### ISSUE TITLE
7.3.4_React에서 에러 바운더리 사용시 이점이 무엇인가요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#20]
📝 231p

❓ React에서 에러 바운더리 사용시 이점이 무엇인가요?

**Comment by 42inshin** [comment]
리액트의 에러 바운더리를 사용하면, 하위 컴포넌트에서 생긴 에러들을 에러 바운더리 컴포넌트로 올려 발생한 컴포넌트 대신 에러를 처리하고, 에러 시 보여줄 공통된 컴포넌트를 렌더링할 수 있습니다.

**Comment by jnkeniaem** [comment]
리액트 컴포넌트 트리 하위에 있는 컴포넌트에서의 예상치 못한 에러의 발생 여부를 추적하고 그 에러를 공통 처리할 때 유용하게 사용할 수 있습니다.
