### ISSUE TITLE
8.1.7_리액트에서 forwardRef 를 어떤 때 사용할까요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#22]
📝 267p

❓리액트에서 forwardRef 를 어떤 때 사용할까요?

**Comment by 42inshin** [comment]
부모 컴포넌트가 자식 컴포넌트의 DOM 요소에 접근해야 할 때 사용됩니다. 예를 들어, 부모 컴포넌트가 자식 컴포넌트의 버튼에 focus를 설정해야 하는 경우에 사용합니다.

**Comment by jnkeniaem** [comment]
html 요소가 아닌 리액트 컴포넌트에서 ref prop을 사용할때 사용합니다. 리액트 컴포넌트를 forwardRef 함수로 감싸주면, 해당 컴포넌트는 두 번째 매개변수를 갖게되는데, 이를 통해 외부에서 ref prop을 전달할 수 있습니다.
