### ISSUE TITLE
8.2.5_useState에서 타입 매개변수를 명시하지 않으면 어떤 문제가 발생할 수 있나요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#24]
📝 272p

❓ useState에서 타입 매개변수를 명시하지 않으면 어떤 문제가 발생할 수 있나요?

**Comment by jnkeniaem** [comment]
useState에 제네릭 타입을 지정해주지 않으면 예상치 못한 타입의 값이 state에 할당될 수 있어 사이드 이펙트가 발생할 수 있습니다.

**Comment by 42inshin** [comment]
타입 매개변수를 명시하지 않으면 초기값을 기반으로 타입을 추론하기 때문에, 정확한 타입을 보장할 수 없다.
