### ISSUE TITLE
9.1.2_useEffect를 사용 시 두번째 인자인 deps에 객체나 배열의 값을 넣어야할 때 주의점

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#25]
📝 291p

❓ useEffect를 사용 시 두번째 인자인 deps에 객체나 배열의 값을 넣어야할 때 어떤 점을 주의해야 하나요? 
(키워드: 얕은 비교)

**Comment by 42inshin** [comment]
useEffect는 deps가 변경되었는지를 얕은 비교로만 판단하기 때문에, 실제 객체 값이 바뀌지 않았더라도 객체의 참조 값이 바뀌면 콜백 함수가 실행 됩니다. 원치 않는 상황에서 렌더링이 일어날 수 있습니다. 해결 방법으로는 객체 내의 실제로 사용하는 값을 deps에 사용하면 됩니다.

**Comment by jnkeniaem** [comment]
실제 객체 값이 바뀌지 않았더라도 객체의 참조 값이 변경되면 불필요하게 콜백 함수가 실행되고 성능저하로 이어질 수 있게 때문에 문자열이나 숫자와 같은 기본 자료형이 아닌 객체나 배열을 넣을때 주의해야 합니다.
