### ISSUE TITLE
9.1.2_리액트의 메모이제이션에 대해 설명해주세요

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#26]
📝 293p

❓ 리액트의 메모이제이션에 대해 설명해주세요

**Comment by 42inshin** [comment]
메모이제이션은 계산한 결과 값을 저장해, 같은 입력에 대해서 계산하지 않고 저장된 연산 값을 반환하는 최적화 기법입니다.

**Comment by jnkeniaem** [comment]
이전에 계산한 값을 저장함으로써 같은 입력에 대한 연산을 다시 하지 않도록 최적화하는 기술이고, 리액트에서의 주요 메모이제이션 도구로는 useMemo, useCallback이 있습니다.

**Comment by 42inshin** [comment]
꼬리 질문)  useMemo, useCallback에 대해서 사용해 보셨나요? 둘의 사용 방법에 대해서 설명해주세요
