### ISSUE TITLE
10.1_리액트 컨텍스트 API의 한계

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#27]
📝 306, 319p

❓ 전역 상태를 관리할때 리액트 컨텍스트 API를 사용하는 것보다 외부 상태 관리 라이브러리를 사용하는 것이 더 나은 경우가 있습니다. 리액트 컨텍스트 API의 어떤 한계점 때문일까요?

**Comment by jnkeniaem** [comment]
context provider의 props가 변경될때마다 해당 컨텍스트를 구독하고 있는 모든 컴포넌트가 리렌더링되기 때문에 성능 문제가 발생할 수 있기 때문입니다.

**Comment by 42inshin** [comment]
컨텍스트 API는 React 내장 기능으로 비교적 간단하게 전역 상태 관리를 할 수 있습니다. 하지만 대규모 애플리케이션이나 중요한 애플리케이션에서는 권장되지 않습니다. 그 이유는 컨텍스트 프로바이더의 props로 주입된 값이나 참조가 업데이트될 때마다 구독하고 있는 모든 컴포넌트가 다시 렌더링되기 때문입니다. 성능 저하와 복잡성을 늘릴 수 있어서, 중요한 앱의 경우 중앙에서 상태를 관리할 수 있는 상태 관리 라이브러리를 사용합니다.
