### ISSUE TITLE
10.1.1_Prop drilling에 대해서 설명하고, 해당 문제를 피하기 위해서 어떤 방식을 이용하나요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#28]
📝 307p

❓ Prop drilling에 대해서 설명하고, 해당 문제를 피하기 위해서 어떤 방식을 이용하나요?

**Comment by 42inshin** [comment]
props drilling은 prop을 통해 데이터를 전달하는 과정에서 데이터가 필요하지 않음에도 자식 컴포넌트에게 데이터를 전달하기 위해 중간 컴포넌트에도 prop을 계속해서 전달해야하는 현상을 말합니다. 
이런 문제를 해결하기 위해 전역 상태, 상태 관리 라이브러리들을 사용합니다.

**Comment by jnkeniaem** [comment]
props로 데이터를 하위 컴포넌트로 전달하는 과정에서 그 사이에 있는 중간 컴포넌트는 해당 데이터가 필요하지 않는데도 props로 전달해야 하는 과정이고, 이로 인해 코드가 훨씬 복잡해질 수 있습니다.
이 문제를 해결하기 위해선, 전역 상태 관리 api와 상태 관리 라이브러리를 통해 지역 상태를 전역 상태로 공유합니다.
