### ISSUE TITLE
11.1.2_CSS-in-JS의 등장으로 HTML, CSS, JS 단위로 분리하던 이전 방식에서 어떤 점이 바뀌었나요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#29]
📝 331, 332p

❓ CSS-in-JS의 등장으로 HTML, CSS, JS 단위로 웹 애플리케이션을 분리하던 이전 방식에서 어떤 점이 바뀌었나요?

**Comment by 42inshin** [comment]
바뀐점 중 가장 큰 부분은 컴포넌트 단위로 추상화하여 관리할 수 있다는 점입니다. 
또한 스타일의 클래스 이름을 컴포넌트마다 고유하게 생성해줘 클래스 이름 고민을 하는 것에 대한 고민을 줄여주고, 선택자 충돌을 방지해주는 등의 장점이 있습니다. 
그리고 props 를 받아 상태 값에 따라 다른 스타일을 적용해줄 수 있어, js와 css간에 상태 값을 공유할 수 있다는 장점이 있습니다.

**Comment by jnkeniaem** [comment]
css-in-js를 통해 자바스크립트의 변수, 함수를 스타일 코드 내에서 쉽게 사용할 수 있게 됐습니다. 즉, 스타일과 이를 제어하는 자바스크립트 로직을 한 파일 내에서 관리할 수 있게 됐습니다.
