### ISSUE TITLE
2.4.5_호출 시그니처와 함수 타입 표현식

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#3]
📝 78p

❓❗️ **호출 시그니처에 대해 예시가 적혀 있는데, 해당 내용을 찾아보니 아래 예시처럼 적는건 `함수 타입 표현식` 이라고 합니다.  책에서는 두 가지 용어를 혼재해서 사용하는 것 같아요. 짚고 넘어가는게 좋을 것 같아서 기록합니다.**
```typescript
type Add = (a: number, b: number) => number; // 함수 타입 표현식
```

### 함수 타입 표현식
```typescript
type Operation = (a: number, b: number) => number;

const add: Operation = (a, b) => a + b;

```

### 호출 시그니처
```typescript
type Operation2 = {
  (a: number, b: number): number;
};

const add2: Operation2 = (a, b) => a + b;
```

## 요약
**함수 타입 표현식 (Function Type Expressions)**: 함수의 매개변수와 반환 타입을 정의하는 방법으로, 주로 변수나 매개변수의 타입을 정의할 때 사용됩니다.
**호출 시그니처 (Call Signatures)**: 인터페이스나 객체 타입 내에서 함수의 타입을 정의하는 방법으로, 주로 객체의 메서드 타입을 정의할 때 사용됩니다.

**Comment by jnkeniaem** [comment]
오호 그렇군요..! 잘못된 지식 굳힐뻔했네요.. 공유 감사합니다 !
