### ISSUE TITLE
11.1.1_인라인 스타일과 css-in-js의 차이점

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#30]
📝 328p

❓ 인라인 스타일과 css-in-js의 차이점을 말해주세요

**Comment by jnkeniaem** [comment]
인라인 스타일은 HTML 요소에 스타일을 직접 적용하기 때문에, 동일한 스타일을 여러 곳에 적용해야 할 때 코드 중복이 발생할 수 있습니다. 즉, 재사용성이 낮습니다.
반면에 CSS-in-JS는 한 곳에서 정의한 스타일을 여러 컴포넌트에서 재사용할 수 있고, 유지보수가 용이합니다.

**Comment by 42inshin** [comment]
인라인 스타일은 HTML 태그에 직접 스타일을 정의하는 방법입니다. JSX내에 직접 스타일을 정의할 수 있어 간단하고 직관적입니다. 단점으로는 동일한 스타일을 여러 컴포넌트에서 사용할 때 중복 코드가 발생할 수 있습니다. 또한, css와 동일하지 않은 속성이름들이 존재(backgroud-color -> backgroundColor)해서 혼동이 있기도 합니다. 미디어쿼리나 :hover와 같은 css의 기능을 지원하지 않습니다.

CSS-in-JS는 스타일을 컴포넌트 단위로 정의할 수 있고, props과 같은 상수, 변수 들을 받아서 스타일을 변경할 수 있고 재사용성이 용이합니다. 그리고 미디어쿼리, 의사 클래스(:hover, :focus), 애니메이션 등 css의 모든 기능을 지원합니다. 
단점으로는 CSS-in-JS 라이브러리를 사용해야 해서 추가적인 학습이 필요합니다.
