### ISSUE TITLE
12.1.1_앰비언트 타입 선언 시 사용되는 키워드와 활용 사례를 말씀해주세요

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#31]
📝 338p

.d ts 확장자를 가진 파일에서 하는 타입 선언을 앰비언트(ambient) 타입 선언이라고 합니다. 

❓ 앰비언트 타입 선언 시 사용되는 키워드를 말씀해 주세요.
❓ 앰비언트 타입 선언은 활용사례를 하나 이상 말씀해 주세요.

**Comment by 42inshin** [comment]
앰비언트 타입 선언 시 사용하는 키워드는 `declare` 입니다.

자바스크립트로 작성된 라이브러리에 앰비언트 타입 선언을 해서 any 타입으로 추론되는 것을 방지할 수 있습니다.
또한, 자바스크립트 어딘가에 전역 변수가 정의되어 있지만 타입스크립트로 구현되지 않은 변수들에 대해 타입 선언을 할 때에도 사용합니다.
웹뷰를 개발할 때, Window 객체에서 deviceId나 appVersion 같은 값을 받아오기 위해서 global namespace에 있는 window 객체에 해당 속성을 정의해 에러를 방지할 수 있습니다.

**Comment by jnkeniaem** [comment]
declare 키워드를 사용하고, .js와 .ts 형식 외의 파일(.png)을 임포트할때, 그리고 자바스크립트 코드 어딘가에 전역 변수나 객체가 정의돼 있음을 타입스크립트에 알릴때 앰비언트 타입 선언을 사용합니다.
