### ISSUE TITLE
12.1.1_앰비언트 타입 선언이란 무엇인가요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#32]
📝 338p

❓ 앰비언트 타입 선언이란 무엇이고, 어떤 경우에 사용하는 것이 좋을까요?

**Comment by 42inshin** [comment]
앰비언트 타입 선언은 `.d.ts` 파일에서 타입을 선언하는 방식으로, 값을 직접 정의하지 않고 `declare` 키워드를 사용해 어딘가에 값이 존재한다는 사실을 알리는 것을 말합니다. 


자바스크립트로 작성된 라이브러리에 앰비언트 타입 선언을 해서 any 타입으로 추론되는 것을 방지할 수 있습니다.
또한, 자바스크립트 어딘가에 전역 변수가 정의되어 있지만 타입스크립트로 구현되지 않은 변수들에 대해 타입 선언을 할 때에도 사용합니다.
웹뷰를 개발할 때, Window 객체에서 deviceId나 appVersion 같은 값을 받아오기 위해서 global namespace에 있는 window 객체에 해당 속성을 정의해 에러를 방지할 수 있습니다.

**Comment by jnkeniaem** [comment]
타입스크립트가 기본적으로 알지 못하는 변수나 모듈 등을 타입스크립트 컴파일러에게 알려주는 타입 선언 입니다.
타입스크립트는 기본적으로 .js와 .ts 파일만 이해합니다. 그래서 그 외의 파일(.png)을 임포트할때 앰비언트 타입 선언을 사용합니다.
