### ISSUE TITLE
12.4_여러 개의 프로젝트를 관리해야 하는 경우, 어떤 방식으로 프로젝트들을 관리할건가요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#33]
📝 356p

❓ 여러 개의 프로젝트를 관리해야 하는 경우, 어떤 방식으로 프로젝트들을 관리할건가요?

**Comment by 42inshin** [comment]
프로젝트가 많지 않다면 멀티 레포 형식으로 관리할 것 같습니다. 공통 요소들을 찾아서 중복 코드를 관리하고, 공통 부분들을 모듈화해서 관리할 수 도 있을 것 같습니다. 
만약, 확장 가능성이 있는 대형 프로젝트라면, 모노레포 방식을 채택해 하나의 레포지토리로 통합해서 각 패키지들을 개별적인 버저닝을 통해 관리하면 좋을 것 같습니다.

**Comment by jnkeniaem** [comment]
하나의 레포지토리로 모든 것을 관리해서 lint, ci/cd 등 개발 환경 설정도 통합적으로 관리해서 불필요한 코드 중복을 막아 줄 수 있는 모노 레포 방식을 선택할것같습니다.
