### ISSUE TITLE
12.3.3_타입스크립트 마이그레이션 단계에 대해 설명해주세요

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#34]
📝 356p

❓타입스크립트 마이그레이션 단계에 대해 allowJS, noImplicitAny 옵션을 포함해서 설명해주세요.

**Comment by 42inshin** [comment]
자바스크립트로 만든 프로젝트에서 타입스크립트로 마이그레이션 하는 경우, 한번에 진행하기 어려운 경우, 점진적으로 진행할 것이다.
그런 경우 allowJS: true, noImplicitAny: false로 두고, 자바스크립트와 타입스크립트의 import 호환이 되게 설정해주고 any 타입을 허용해서 하나씩 작업을 한다.
모든 파일을 타입스크립트로 바꾸었다면, 다시 allowJS: false, noImplicitAny: true 로 설정을 바꿔 타입이 명시되지 않은 부분을 점검한다.

**Comment by jnkeniaem** [comment]
1. 타입스크립트 개발 환경을 설정.
    오류가 발생하지 않도록 tsconfig.json 파일에서 allowJS를 true로, noImplicitAny를 false로 설정.
    - allowJS true이면 기존 자바스크립트 함수를 타입스크립트에서 임포트하거나, 반대로 타입스크립트 함수를 자바스크립트에서 임포트할 수 있게 해줌
    - noImplicitAny true면 any 타입이 있을 때 오류가 발생시킴
2. 작성된 자바스크립트 파일을 타입스크립트 파일로 변환. 필요한 타입과 인터페이스를 하나씩 정의해 함수나 변수에 타입을 추가
3. tsconfig.json 파일에서 allowJS를 false로, noImplicitAny를 true로 설정 → 타입이 명시되지 않은 부분이 없는지 점검
