### ISSUE TITLE
13.3_캡슐화가 무엇인가요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#35]
📝 374p

❓ 캡슐화가 무엇인가요?

**Comment by jnkeniaem** [comment]
캡슐화는 다른 객체 내부의 데이터를 꺼내와서 직접 다루지 않고, 해당 객체에서 처리할 행동을 따로 요청함으로써 협력하는 것 입니다.
예시를 들자면, 리액트에서 컴포넌트는 객체이고, 내부의 데이터인 state가 캡슐화의 대상이 될 수 있습니다.

**Comment by 42inshin** [comment]
캡슐화는 객체에 필요한 값과 매서드를 하나의 단위로 묶는 방식으로, 내부 상태를 외부에서 직접 접근하지 못하도록 하여 데이터의 무결성을 유지하는 방식입니다. 프론트엔드에서는 컴포넌트 객체와 상태, props의 관계가 캡슐화라고 할 수 있습니다.
