### ISSUE TITLE
13.1_객체 지향 관점에서 프론트엔드 프로젝트에 타입스크립트가 어떤 이점을 주나요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#36]
📝 365p

❓ 객체 지향 관점에서 프론트엔드 프로젝트에 타입스크립트가 어떤 이점을 주나요?

**Comment by 42inshin** [comment]
1. 타입스크립트는 props을 정의할 수 있다. 즉, 인터페이스와 타입을 정의할 수 있어서 객체의 구조를 명확하게 만든다.
2. 구조적 타이핑을 따르기 때문에 객체 지향의 폭을 넓혀준다.
3. 접근 제어자를 제공하기 때문에 클래스의 멤버 범위를 제어할 수 있다.

**Comment by jnkeniaem** [comment]
타입스크립트는 프로퍼티와 메서드의 형태를 기준으로 타입호환성을 판단하는 구조적 타이핑을 사용합니다.
객체 지향 설계에서는 객체 간 협력이 중요한데, 구조적 타이핑은 의도치 않은 경직성을 줄이고 객체 간 상호작용을 자연스럽게 만듭니다. 예를 들어, 함수의 매개변수로 여러 타입의 객체를 받을 때, 구조가 맞다면 타입 강제를 피할 수 있습니다.
