### ISSUE TITLE
2.2.2_구조적 타이핑과 명목적 타이핑의 차이점은 무엇인가요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#4]
📝 43p

❓ 구조적 타이핑과 명목적 타이핑의 차이점은 무엇인가요?

**Comment by 42inshin** [comment]
구조적 타이핑은 객체의 구조를 기준으로 타입을 검사합니다. 즉, 객체의 속성과 타입이 일치하면 같은 타입으로 간주합니다.
반면에, 명목적 타이핑은 객체의 이름을 기준으로 타입을 검사합니다. 객체의 속성이 동일하더라도 다른 이름인 경우에는 다른 타입으로 간주합니다.
타입스크립트는 구조적 타이핑을 따르며, 명목적 타이핑의 예로는 자바가 있습니다.

**Comment by jnkeniaem** [comment]
명목적 타입은 타입이 이름으로 구분된다.
구조적 타이핑은 객체가 가지고 있는 속성(프로퍼티), 메서드를 바탕으로 타입을 구분하는 것. 이름이 다른 객체라도 가진 속성이 동일하다면 서로 호환이 가능한 동일한 타입으로 여긴다.
