### ISSUE TITLE
2.1.2_강타입과 약타입의 분류 기준이 무엇인가요?

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#5]
📝 38p

❓ 강타입과 약타입의 분류 기준이 무엇인가요?
서로 다른 타입을 갖는 값 끼리 연산 시도 했을때 각각의 특징을 갖는 언어에서의 처리 프로세스는 어떻게 되나요?

[참고 프론트엔드 채용 공고](https://www.rallit.com/positions/2126/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C-%EA%B0%9C%EB%B0%9C%EC%9E%90-react-typescript)    

 
우대사항
• TypeScript 등 강타입 (Strongly Typed) 언어를 이해하고 있으신 분

**Comment by jnkeniaem** [comment]
암묵적 타입 변환 여부에 따라 분류할 수 있다.
강타입의 언어에선 컴파일러 또는 인터프리터에서 에러가 발생,
약타입의 언어에선 컴파일러 또는 인터프리터가 내부적으로 판단해서 특정 값의 타입을 변환해서 연산한 후 값을 낸다

**Comment by 42inshin** [comment]
개발자의 의도와 상관없이 컴파일러나 엔진에서 암묵적으로 타입이 자동 변환되는 것을 암묵적 타입 변환이라고 하는데, 이러한 타입 변화가 일어나는 언어를 약타입 언어라고 부르며, 컴파일러나 인터프리터에서 타입 오류 등을 잡아내어 암묵적 타입 변환을 허용하지 않는 언어를 강타입 언어라고 부른다. 즉, 암묵적 타입 변환의 허용 유무에 따라 강타입, 약타입을 구분 짓는다.
