### ISSUE TITLE
3.1.5_타입스크립트의 배열은 자바스크립트의 배열과 어떤 점이 다른가요?

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#6]
📝 90p 

❓ 타입스크립트의 배열은 자바스크립트의 배열과 어떤 점이 다른가요?

**Comment by 42inshin** [comment]
자바스크립트는 동적 타입 언어로, 배열에 여러가지 타입들의 값을 추가할 수 있습니다. 반면에, 타입스크립트는 정적 타입 언어로, 배열의 요소 타입을 명시적으로 지정할 수 있으며, 배열의 모든 요소가 지정된 타입을 따라야 합니다.
또한, 여러 타입을 가질 수 있도록 유니온 타입을 사용할 수 있고, 배열의 길이와 각 요소의 타입을 고정할 수 있는 튜플 타입을 지원합니다.

**Comment by jnkeniaem** [comment]
자스에서 하나의 배열로 선언된 변수에 숫자, 문자열 등의 다양한 자료형의 값을 원소로 가질 수 있다.
반면 타스에 배열의 원소는 ~하나의 타입으로만~ 선언시 지정한 타입으로만 이뤄진다.
