### ISSUE TITLE
3.1.6_열거형을 선언하는 방식 두가지 enum, const enum 중 후자가 더 안전한 이유를 설명해주세요

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#7]
📝 97p

❓ 열거형을 선언하는 방식 두가지 enum, const enum 중 후자가 더 안전한 이유를 설명해주세요

---

**Issue Checklist**
- [ ] assignees
- [ ] label

**Comment by jnkeniaem** [comment]
```
enum ProgrammingLanguage {
  Typescript, // 0
  Javascript, // 1
}
```
`enum` 키워드로 열거형 선언시 `ProgrammingLanguage[1]; // “JavaScript”`와 같이 역방향으로 접근할 수 있다.
이때 할당된 값을 넘어가는 범위로 접근해도 `undefined`를 출력할 뿐 타스는 에러를 발생시키지 않는다. 
반면에 `const enum`을 사용하면 역방향으로의 접근을 허용하지 않아서 이런 에러를 방지해 `enum` 보다 안전하다.

**Comment by 42inshin** [comment]
숫자로만 이루어진 enum을 사용하면 역방향으로 접근이 가능하다. 여기서 문제가 있는데, enum에서 선언하지 않은 값에 접근해도 별 다른 에러를 발생하지 않는다. const enum을 사용하면 역방향 접근을 허용하지 않기 때문에 후자가 더 안전하다.

추가로, const enum은 컴파일 시 인라인(직접 값으로 대체 됨)으로 대체되어서, 런타임 오류를 줄이고, 코드 크기가 감소하고, 불변성을 보장하는 장점이 있다.

```ts
enum Number {
  One, // 0
  Two, // 1
}

Number[100] // undefined를 출력하지만 별다른 에러를 발생시키지 않는다.
```

#### const enum 인라인

const enum의 경우, 열거형 값을 사용한 위치에 해당 값이 직접 삽입됩니다.

```ts
const enum Direction {
    Up,
    Down,
    Left,
    Right
}

let dir: Direction = Direction.Up;
```

컴파일된 JavaScript 코드에서는 Direction.Up이 직접 값으로 대체됩니다:

```ts
"use strict";
var dir = 0 /* Direction.Up */;
```
