### ISSUE TITLE
3.2.3_interface에서 동적으로 추가될 속성의 키, 값의 타입을 고정하는 방법

### ISSUE THREAD

**Issue by 42inshin** [Frontend-Gang-Study/woowahan-typescript-with-react#8]
📝 100p

❓ interface에서 동적으로 추가될 속성의 키와 값에 대한 타입을 고정해둘 수 있는데, 뭐라고 부르고, 어떻게 작성해야할까요?

**Comment by jnkeniaem** [comment]
인덱스 시그니처라 부르고, `[Key : K]: T `형태로 타입을 명시합니다.
해당 타입의 속성 키는 모두 K 타입이어야 하고, 속성값은 모두 T 타입을 가져야 합니다.

**Comment by 42inshin** [comment]
interface에서 키와 값을 고정하는 방법은 "인덱스 시그니처"라고 부르고 `[key: K]: T` 꼴로 사용합니다.
아래는 예시 코드입니다.

```ts
interface IndexSignature {
   [key: string]: number;
}
```
