### ISSUE TITLE
3.3.6_제네릭 사용의 장점

### ISSUE THREAD

**Issue by jnkeniaem** [Frontend-Gang-Study/woowahan-typescript-with-react#9]
📝 115p

❓ 타입스크립트의 제네릭 사용의 장점을 설명해주세요

**Comment by jnkeniaem** [comment]
제네릭을 통해 여러 타입을 받아 처리할 수 있어 코드를 효율적으로 재사용 가능하고, 가독성도 높일 수 있고, 타입 추론 및 타입 검사가 가능합니다.

**Comment by 42inshin** [comment]
동일한 로직을 여러 타입에 대해 재사용할 수 있어서, 재사용성이 좋고, 각 타입마다 작성하지 않아도 되기 때문에 가독성이 좋아집니다.
